# Generated by Django 5.0.7 on 2024-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('c_number', models.IntegerField()),
                ('courses', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
